return {
	{
		name = "tokyonight",
		repo = "folke/tokyonight.nvim",
		description = "🏙 A clean, dark Neovim theme written in Lua, with support for lsp, treesitter and lots of plugins. Includes additional themes for Kitty, Alacritty, iTerm and Fish. ",
		tags = { "dark", "clean", "customizable" },
		install_path = "tokyonight.nvim",
		variants = {
			{ name = "tokyonight-storm", display = "storm" },
			{ name = "tokyonight-day", display = "Day" },
			{ name = "tokyonight-moon", display = "Moon" },
			{ name = "tokyonight-night", display = "Night" },
		},
	},
	{
		name = "catppuccin",
		repo = "catppuccin/nvim",
		description = "🍨 Soothing pastel theme for (Neo)vim ",
		tags = { "pastel", "light", "dark" },
		install_path = "catppuccin",
		variants = {
			{ name = "catppuccin-frappe", display = "Catpuccin Frappe" },
			{ name = "catppuccin-latte", display = "Catpuccin Latte" },
			{ name = "catppuccin-macchiato", display = "Catpuccin Macchiato" },
			{ name = "catppuccin-mocha", display = "Catpuccin Mocha" },
			{ name = "catppuccin", display = "Catpuccin" },
		},
	},
	{
		name = "kanagawa",
		repo = "rebelot/kanagawa.nvim",
		description = "NeoVim dark colorscheme inspired by the colors of the famous painting by Katsushika Hokusai. ",
		tags = { "dark", "artistic" },
		install_path = "kanagawa.nvim",
		variants = {
			{ name = "kanagawa-dragon", display = "Kanagawa Dragon" },
			{ name = "kanagawa-lotus", display = "Kanagawa Lotus" },
			{ name = "kanagawa-wave", display = "Kanagawa Wave" },
			{ name = "kanagawa", display = "Kanagawa" },
		},
	},
	{
		name = "nightfox",
		repo = "EdenEast/nightfox.nvim",
		description = "🦊A highly customizable theme for vim and neovim with support for lsp, treesitter and a variety of plugins. ",
		tags = { "dark", "customizable" },
		install_path = "nightfox.nvim",
		variants = {
			{ name = "nightfox", display = "Nightfox" },
			{ name = "dayfox", display = "Dayfox" },
			{ name = "dawnfox", display = "Dawnfox" },
			{ name = "duskfox", display = "Duskfox" },
			{ name = "nordfox", display = "Nordfox" },
			{ name = "terafox", display = "Terafox" },
			{ name = "carbonfox", display = "Carbonfox" },
		},
	},
	{
		name = "rose-pine",
		repo = "rose-pine/neovim",
		description = "Soho vibes for Neovim ",
		tags = { "calm", "pastel", "light", "dark" },
		install_path = "rose-pine",
		variants = {
			{ name = "rose-pine-dawn", display = "Rose Pine Dawn" },
			{ name = "rose-pine-main", display = "Rose Pine Main" },
			{ name = "rose-pine-moon", display = "Rose Pine Moon" },
			{ name = "rose-pine", display = "Rose Pine" },
		},
	},
	{
		name = "onedark",
		repo = "navarasu/onedark.nvim",
		description = "One dark and light colorscheme for neovim >= 0.5.0 written in lua based on Atom's One Dark and Light theme. Additionally, it comes with 5 color variant styles ",
		tags = { "dark" },
		install_path = "onedark.nvim",
	},
	{
		name = "oxocarbon",
		repo = "nyoom-engineering/oxocarbon.nvim",
		description = "A dark and light Neovim theme written in fennel, inspired by IBM Carbon. ",
		tags = { "dark", "light", "professional" },
		install_path = "oxocarbon.nvim",
	},
	{
		name = "vim-moonfly-colors",
		repo = "bluz71/vim-moonfly-colors",
		description = "Dark charcoal theme for modern Neovim & classic Vim.",
		tags = { "dark", "charcoal" },
		install_path = "vim-moonfly-colors",
		custom_name = "moonfly",
	},
	{
		name = "onedarkpro",
		repo = "olimorris/onedarkpro.nvim",
		description = "🎨 Atom's iconic One Dark theme. Cacheable, fully customisable, Tree-sitter and LSP semantic token support. Comes with variants ",
		tags = { "dark", "customizable" },
		install_path = "onedarkpro.nvim",
		custom_name = "onedark",
		variants = {
			{ name = "onedark", display = "Onedark" },
			{ name = "onedark_dark", display = "Onedark Dark" },
			{ name = "onedark_vivid", display = "Onedark Vivid" },
			{ name = "onelight", display = "Onelight" },
			{ name = "vaporwave", display = "Vaporwave" },
		},
	},
	{
		name = "vim-nightfly-colors",
		repo = "bluz71/vim-nightfly-colors",
		description = "A dark midnight theme for modern Neovim & classic Vim ",
		tags = { "dark", "midnight" },
		install_path = "vim-nightfly-colors",
		custom_name = "nightfly",
	},
	{
		name = "nord",
		repo = "shaunsingh/nord.nvim",
		description = "Neovim theme based off of the Nord Color Palette, written in lua with tree sitter support ",
		tags = { "dark", "cool" },
		install_path = "nord.nvim",
	},
	{
		name = "nord",
		repo = "gbprod/nord.nvim",
		description = "An arctic, north-bluish clean and elegant Neovim theme.",
		tags = { "dark", "cool" },
		install_path = "nord.nvim",
	},
	{
		name = "nordic",
		repo = "AlexvZyl/nordic.nvim",
		description = "🌒 Nord for Neovim, but warmer and darker. Supports a variety of plugins and other platforms. ",
		tags = { "dark", "warm" },
		install_path = "nordic.nvim",
	},
	{
		name = "onenord",
		repo = "rmehri01/onenord.nvim",
		description = "🏔️ A Neovim theme that combines the Nord and Atom One Dark color palettes for a more vibrant programming experience. ",
		tags = { "dark", "cool" },
		install_path = "onenord.nvim",
		variants = {
			{ name = "onenord-light", display = "Onenord Light" },
			{ name = "onenord", display = "Onenord" },
		},
	},
	{
		name = "melange",
		repo = "savq/melange-nvim",
		description = "🗡️ Warm color scheme for Neovim and beyond ",
		tags = { "warm", "terminal-friendly" },
		install_path = "melange-nvim",
	},
	{
		name = "neovim-ayu",
		repo = "Shatur/neovim-ayu",
		description = "Ayu theme port for Neovim.",
		tags = { "light", "dark", "soft" },
		install_path = "neovim-ayu",
		custom_name = "ayu",
		variants = {
			{ name = "ayu-dark", display = "Ayu Dark" },
			{ name = "ayu-light", display = "Ayu Light" },
			{ name = "ayu-mirage", display = "Ayu Mirage" },
			{ name = "ayu", display = "Ayu" },
		},
	},
	{
		name = "gruvbox",
		repo = "ellisonleao/gruvbox.nvim",
		description = "Lua port of the most famous vim colorscheme ",
		tags = { "dark", "warm", "retro" },
		install_path = "gruvbox.nvim",
	},
	{
		name = "gruvbox-material",
		repo = "sainnhe/gruvbox-material",
		description = "Gruvbox with Material Palette ",
		tags = { "dark", "warm", "retro" },
		install_path = "gruvbox-material",
	},
	{
		name = "gruvbox-baby",
		repo = "luisiacc/gruvbox-baby",
		description = "Gruvbox theme for neovim with full 🎄TreeSitter support. ",
		tags = { "dark", "warm", "retro" },
		install_path = "gruvbox-baby",
	},
	{
		name = "miasma",
		repo = "xero/miasma.nvim",
		description = "a fog descends upon your editor ☁ dark color scheme inspired by the woods for vim and neovim ",
		tags = { "dark", "moody" },
		install_path = "miasma.nvim",
	},
	{
		name = "bamboo",
		repo = "ribru17/bamboo.nvim",
		description = "Warm Green Theme for Neovim and Beyond ",
		tags = { "warm", "green" },
		install_path = "bamboo.nvim",
		variants = {
			{ name = "bamboo-light", display = "Bamboo Light" },
			{ name = "bamboo-multiplex", display = "Bamboo Multiplex" },
			{ name = "bamboo-vulgaris", display = "Bamboo Vulgaris" },
			{ name = "bamboo", display = "Bamboo" },
		},
	},
	{
		name = "everforest",
		repo = "sainnhe/everforest",
		description = "🌲 Comfortable & Pleasant Color Scheme for Vim ",
		tags = { "calm", "dark", "forest" },
		install_path = "everforest",
	},
	{
		name = "night-owl",
		repo = "oxfist/night-owl.nvim",
		description = "🦉 🌌 Night Owl colorscheme implementation for Neovim with support for Treesitter and semantic tokens ",
		tags = { "dark", "night", "treesitter" },
		install_path = "night-owl.nvim",
	},
	{
		name = "tender",
		repo = "jacoborus/tender.vim",
		description = "A 24bit colorscheme for Vim, Airline and Lightline ",
		tags = { "24-bit", "colorful" },
		install_path = "tender.vim",
	},
	{
		name = "cyberdream",
		repo = "scottmckendry/cyberdream.nvim",
		description = "🤖💤 High-contrast, Futuristic & Vibrant Neovim Colorscheme ",
		tags = { "vibrant", "futuristic", "high-contrast" },
		install_path = "cyberdream.nvim",
		variants = {
			{ name = "cyberdream-light", display = "Cyberdream Light" },
			{ name = "cyberdream", display = "Cyberdream" },
		},
	},
	{
		name = "zenbones",
		repo = "zenbones-theme/zenbones.nvim",
		description = "🪨 A collection of contrast-based Vim/Neovim colorschemes ",
		tags = { "minimal", "monochrome", "contrast" },
		requires_lush = true,
		install_path = "zenbones.nvim",
		variants = {
			{ name = "duckbones", display = "Duckbones" },
			{ name = "forestbones", display = "Forestbones" },
			{ name = "kanagawabones", display = "Kanagawabones" },
			{ name = "neobones", display = "Neobones" },
			{ name = "nordbones", display = "Nordbones" },
			{ name = "randombones", display = "Randombones" },
			{ name = "rosebones", display = "Rosebones" },
			{ name = "seoulbones", display = "Seoulbones" },
			{ name = "tokyobones", display = "Tokyobones" },
			{ name = "vimbones", display = "Vimbones" },
			{ name = "zenbones", display = "Zenbones" },
			{ name = "zenburned", display = "Zenburned" },
			{ name = "zenwritten", display = "Zenwritten" },
		},
	},
	{
		name = "vague",
		repo = "vague2k/vague.nvim",
		description = "A cool, dark, low contrast colorscheme for Neovim. Pastel yet vivid, like a fleeting memory... ",
		tags = { "dark", "low-contrast" },
		install_path = "vague.nvim",
	},
	{
		name = "vesper",
		repo = "datsfilipe/vesper.nvim",
		description = "It's a port of the popular VS Code theme Vesper, written in Lua.",
		tags = { "dark", "vibrant" },
		install_path = "vesper.nvim",
	},
	{
		name = "abstract-cs",
		repo = "Abstract-IDE/Abstract-cs",
		description = "Colorscheme written in Lua, specially made for roshnivim with Tree-sitter support.",
		tags = { "dark", "treesitter" },
		install_path = "Abstract-cs",
		custom_name = "abscs",
	},
	{
		name = "neon",
		repo = "rafamadriz/neon",
		description = "Customizable colorscheme with excellent italic and bold support, dark and light variants. Made to work and look good with Tree-sitter.",
		tags = { "dark", "light", "customizable" },
		install_path = "neon",
	},
	{
		name = "vim-code-dark",
		repo = "tomasiser/vim-code-dark",
		description = "A dark color scheme heavily inspired by the look of the Dark+ scheme of Visual Studio Code.",
		tags = { "dark", "vibrant" },
		install_path = "vim-code-dark",
		custom_name = "codedark",
	},
	{
		name = "vscode",
		repo = "Mofiqul/vscode.nvim",
		description = "A Lua port of vim-code-dark colorscheme with vscode light and dark theme.",
		tags = { "dark", "light", "vibrant" },
		install_path = "vscode.nvim",
	},
	{
		name = "visual_studio_code",
		repo = "askfiy/visual_studio_code",
		description = "A Neovim theme that highly restores vscode, so that your friends will no longer be surprised that you use Neovim, because they will think you are using vscode.",
		tags = { "dark", "light", "vibrant" },
		install_path = "visual_studio_code",
	},
	{
		name = "material",
		repo = "marko-cerovac/material.nvim",
		description = "Material.nvim is a highly configurable colorscheme written in Lua and based on the material palette.",
		tags = { "dark", "light", "customizable" },
		install_path = "material.nvim",
		variants = {
			{ name = "material-darker", display = "Material Darker" },
			{ name = "material-deep-ocean", display = "Material Deep Ocean" },
			{ name = "material-lighter", display = "Material Lighter" },
			{ name = "material-oceanic", display = "Material Oceanic" },
			{ name = "material-palenight", display = "Material Palenight" },
			{ name = "material", display = "Material" },
		},
	},
	{
		name = "evergarden",
		repo = "comfysage/evergarden",
		description = "A comfy Neovim colorscheme for cozy morning coding.",
		tags = { "calm", "dark", "light" },
		install_path = "evergarden",
		variants = {
			{ name = "evergarden-fall", display = "Evergarden Fall" },
			{ name = "evergarden-spring", display = "Evergarden Spring" },
			{ name = "evergarden-summer", display = "Evergarden Summer" },
			{ name = "evergarden-winter", display = "Evergarden Winter" },
			{ name = "evergarden", display = "Evergarden" },
		},
	},
	{
		name = "sonokai",
		repo = "sainnhe/sonokai",
		description = "High Contrast & Vivid Color Scheme based on Monokai Pro.",
		tags = { "dark", "vibrant", "high-contrast" },
		install_path = "sonokai",
	},
	{
		name = "blue-moon",
		repo = "kyazdani42/blue-moon",
		description = "A dark color scheme derived from palenight and carbonight.",
		tags = { "dark", "moody" },
		install_path = "blue-moon",
	},
	{
		name = "oceanic-next",
		repo = "mhartington/oceanic-next",
		description = "Oceanic Next theme.",
		tags = { "dark", "vibrant" },
		install_path = "oceanic-next",
		custom_name = "OceanicNext",
		variants = {
			{ name = "OceanicNext", display = "OceanicNext" },
			{ name = "OceanicNextLight", display = "OceanicNextLight" },
		},
	},
	{
		name = "zephyr",
		repo = "nvimdev/zephyr-nvim",
		description = "A dark colorscheme with Tree-sitter support.",
		tags = { "dark", "treesitter" },
		install_path = "zephyr-nvim",
	},
	{
		name = "boo",
		repo = "rockerBOO/boo-colorscheme-nvim",
		description = "A colorscheme with handcrafted support for LSP, Tree-sitter.",
		tags = { "dark", "treesitter" },
		install_path = "boo-colorscheme-nvim",
		variants = {
			{ name = "boo", display = "Boo" },
			{ name = "crimson_moonlight", display = "Crimson Moonlight" },
			{ name = "forest_stream", display = "Forest Stream" },
			{ name = "radioactive_waste", display = "Radioactive Waste" },
			{ name = "sunset_cloud", display = "Sunset Cloud" },
		},
	},
	{
		name = "modus-theme",
		repo = "ishan9299/modus-theme-vim",
		description = "This is a color scheme developed by Protesilaos Stavrou for emacs.",
		tags = { "dark", "light", "contrast" },
		install_path = "modus-theme-vim",
		custom_name = "modus-vivendi",
		variants = {
			{ name = "modus-operandi", display = "Modus Operandi" },
			{ name = "modus-vivendi", display = "Modus Vivendi" },
		},
	},
	{
		name = "edge",
		repo = "sainnhe/edge",
		description = "Clean & Elegant Color Scheme inspired by Atom One and Material.",
		tags = { "dark", "light", "clean" },
		install_path = "edge",
	},
	{
		name = "aurora",
		repo = "ray-x/aurora",
		description = "A 24-bit dark theme with Tree-sitter and LSP support.",
		tags = { "dark", "treesitter", "24-bit" },
		install_path = "aurora",
	},
	{
		name = "monokai",
		repo = "tanvirtin/monokai.nvim",
		description = "Monokai theme written in Lua.",
		tags = { "dark", "vibrant" },
		install_path = "monokai.nvim",
		variants = {
			{ name = "monokai", display = "Monokai" },
			{ name = "monokai_pro", display = "Monokai Pro" },
			{ name = "monokai_ristretto", display = "Monokai Ristretto" },
			{ name = "monokai_soda", display = "Monokai Soda" },
		},
	},
	{
		name = "base16",
		repo = "RRethy/base16-nvim",
		description = "Neovim plugin for building base16 colorschemes. Includes support for Tree-sitter and LSP highlight groups.",
		tags = { "dark", "light", "customizable" },
		install_path = "base16-nvim",
		custom_name = "base16-0x96f",
		variants = {
			{ name = "base16-0x96f", display = "Base16 0x96f" },
			{ name = "base16-3024", display = "Base16 3024" },
			{ name = "base16-apathy", display = "Base16 Apathy" },
			{ name = "base16-apprentice", display = "Base16 Apprentice" },
			{ name = "base16-ashes", display = "Base16 Ashes" },
			{ name = "base16-atelier-cave-light", display = "Base16 Atelier Cave Light" },
			{ name = "base16-atelier-cave", display = "Base16 Atelier Cave" },
			{ name = "base16-atelier-dune-light", display = "Base16 Atelier Dune Light" },
			{ name = "base16-atelier-dune", display = "Base16 Atelier Dune" },
			{ name = "base16-atelier-estuary-light", display = "Base16 Atelier Estuary Light" },
			{ name = "base16-atelier-estuary", display = "Base16 Atelier Estuary" },
			{ name = "base16-atelier-forest-light", display = "Base16 Atelier Forest Light" },
			{ name = "base16-atelier-forest", display = "Base16 Atelier Forest" },
			{ name = "base16-atelier-heath-light", display = "Base16 Atelier Heath Light" },
			{ name = "base16-atelier-heath", display = "Base16 Atelier Heath" },
			{ name = "base16-atelier-lakeside-light", display = "Base16 Atelier Lakeside Light" },
			{ name = "base16-atelier-lakeside", display = "Base16 Atelier Lakeside" },
			{ name = "base16-atelier-plateau-light", display = "Base16 Atelier Plateau Light" },
			{ name = "base16-atelier-plateau", display = "Base16 Atelier Plateau" },
			{ name = "base16-atelier-savanna-light", display = "Base16 Atelier Savanna Light" },
			{ name = "base16-atelier-savanna", display = "Base16 Atelier Savanna" },
			{ name = "base16-atelier-seaside-light", display = "Base16 Atelier Seaside Light" },
			{ name = "base16-atelier-seaside", display = "Base16 Atelier Seaside" },
			{ name = "base16-atelier-sulphurpool-light", display = "Base16 Atelier Sulphurpool Light" },
			{ name = "base16-atelier-sulphurpool", display = "Base16 Atelier Sulphurpool" },
			{ name = "base16-atlas", display = "Base16 Atlas" },
			{ name = "base16-ayu-dark", display = "Base16 Ayu Dark" },
			{ name = "base16-ayu-light", display = "Base16 Ayu Light" },
			{ name = "base16-ayu-mirage", display = "Base16 Ayu Mirage" },
			{ name = "base16-aztec", display = "Base16 Aztec" },
			{ name = "base16-bespin", display = "Base16 Bespin" },
			{ name = "base16-black-metal-bathory", display = "Base16 Black Metal Bathory" },
			{ name = "base16-black-metal-burzum", display = "Base16 Black Metal Burzum" },
			{ name = "base16-black-metal-dark-funeral", display = "Base16 Black Metal Dark Funeral" },
			{ name = "base16-black-metal-gorgoroth", display = "Base16 Black Metal Gorgoroth" },
			{ name = "base16-black-metal-immortal", display = "Base16 Black Metal Immortal" },
			{ name = "base16-black-metal-khold", display = "Base16 Black Metal Khold" },
			{ name = "base16-black-metal-marduk", display = "Base16 Black Metal Marduk" },
			{ name = "base16-black-metal-mayhem", display = "Base16 Black Metal Mayhem" },
			{ name = "base16-black-metal-nile", display = "Base16 Black Metal Nile" },
			{ name = "base16-black-metal-venom", display = "Base16 Black Metal Venom" },
			{ name = "base16-black-metal", display = "Base16 Black Metal" },
			{ name = "base16-blueforest", display = "Base16 Blueforest" },
			{ name = "base16-blueish", display = "Base16 Blueish" },
			{ name = "base16-brewer", display = "Base16 Brewer" },
			{ name = "base16-bright", display = "Base16 Bright" },
			{ name = "base16-brogrammer", display = "Base16 Brogrammer" },
			{ name = "base16-brushtrees-dark", display = "Base16 Brushtrees Dark" },
			{ name = "base16-brushtrees", display = "Base16 Brushtrees" },
			{ name = "base16-caroline", display = "Base16 Caroline" },
			{ name = "base16-catppuccin-frappe", display = "Base16 Catppuccin Frappe" },
			{ name = "base16-catppuccin-latte", display = "Base16 Catppuccin Latte" },
			{ name = "base16-catppuccin-macchiato", display = "Base16 Catppuccin Macchiato" },
			{ name = "base16-catppuccin-mocha", display = "Base16 Catppuccin Mocha" },
			{ name = "base16-catppuccin", display = "Base16 Catppuccin" },
			{ name = "base16-chalk", display = "Base16 Chalk" },
			{ name = "base16-charcoal-dark", display = "Base16 Charcoal Dark" },
			{ name = "base16-charcoal-light", display = "Base16 Charcoal Light" },
			{ name = "base16-chicago-day", display = "Base16 Chicago Day" },
			{ name = "base16-chicago-night", display = "Base16 Chicago Night" },
			{ name = "base16-circus", display = "Base16 Circus" },
			{ name = "base16-classic-dark", display = "Base16 Classic Dark" },
			{ name = "base16-classic-light", display = "Base16 Classic Light" },
			{ name = "base16-codeschool", display = "Base16 Codeschool" },
			{ name = "base16-colors", display = "Base16 Colors" },
			{ name = "base16-cupcake", display = "Base16 Cupcake" },
			{ name = "base16-cupertino", display = "Base16 Cupertino" },
			{ name = "base16-da-one-black", display = "Base16 Da One Black" },
			{ name = "base16-da-one-gray", display = "Base16 Da One Gray" },
			{ name = "base16-da-one-ocean", display = "Base16 Da One Ocean" },
			{ name = "base16-da-one-paper", display = "Base16 Da One Paper" },
			{ name = "base16-da-one-sea", display = "Base16 Da One Sea" },
			{ name = "base16-da-one-white", display = "Base16 Da One White" },
			{ name = "base16-danqing-light", display = "Base16 Danqing Light" },
			{ name = "base16-danqing", display = "Base16 Danqing" },
			{ name = "base16-darcula", display = "Base16 Darcula" },
			{ name = "base16-darkmoss", display = "Base16 Darkmoss" },
			{ name = "base16-darktooth", display = "Base16 Darktooth" },
			{ name = "base16-darkviolet", display = "Base16 Darkviolet" },
			{ name = "base16-decaf", display = "Base16 Decaf" },
			{ name = "base16-deep-oceanic-next", display = "Base16 Deep Oceanic Next" },
			{ name = "base16-default-dark", display = "Base16 Default Dark" },
			{ name = "base16-default-light", display = "Base16 Default Light" },
			{ name = "base16-digital-rain", display = "Base16 Digital Rain" },
			{ name = "base16-dirtysea", display = "Base16 Dirtysea" },
			{ name = "base16-dracula", display = "Base16 Dracula" },
			{ name = "base16-edge-dark", display = "Base16 Edge Dark" },
			{ name = "base16-edge-light", display = "Base16 Edge Light" },
			{ name = "base16-eighties", display = "Base16 Eighties" },
			{ name = "base16-embers-light", display = "Base16 Embers Light" },
			{ name = "base16-embers", display = "Base16 Embers" },
			{ name = "base16-emil", display = "Base16 Emil" },
			{ name = "base16-equilibrium-dark", display = "Base16 Equilibrium Dark" },
			{ name = "base16-equilibrium-gray-dark", display = "Base16 Equilibrium Gray Dark" },
			{ name = "base16-equilibrium-gray-light", display = "Base16 Equilibrium Gray Light" },
			{ name = "base16-equilibrium-light", display = "Base16 Equilibrium Light" },
			{ name = "base16-eris", display = "Base16 Eris" },
			{ name = "base16-espresso", display = "Base16 Espresso" },
			{ name = "base16-eva-dim", display = "Base16 Eva Dim" },
			{ name = "base16-eva", display = "Base16 Eva" },
			{ name = "base16-evenok-dark", display = "Base16 Evenok Dark" },
			{ name = "base16-everforest-dark-hard", display = "Base16 Everforest Dark Hard" },
			{ name = "base16-everforest-dark-medium", display = "Base16 Everforest Dark Medium" },
			{ name = "base16-everforest-dark-soft", display = "Base16 Everforest Dark Soft" },
			{ name = "base16-everforest", display = "Base16 Everforest" },
			{ name = "base16-flat", display = "Base16 Flat" },
			{ name = "base16-framer", display = "Base16 Framer" },
			{ name = "base16-fruit-soda", display = "Base16 Fruit Soda" },
			{ name = "base16-gigavolt", display = "Base16 Gigavolt" },
			{ name = "base16-github-dark", display = "Base16 Github Dark" },
			{ name = "base16-github", display = "Base16 Github" },
			{ name = "base16-google-dark", display = "Base16 Google Dark" },
			{ name = "base16-google-light", display = "Base16 Google Light" },
			{ name = "base16-gotham", display = "Base16 Gotham" },
			{ name = "base16-grayscale-dark", display = "Base16 Grayscale Dark" },
			{ name = "base16-grayscale-light", display = "Base16 Grayscale Light" },
			{ name = "base16-greenscreen", display = "Base16 Greenscreen" },
			{ name = "base16-gruber", display = "Base16 Gruber" },
			{ name = "base16-gruvbox-dark-hard", display = "Base16 Gruvbox Dark Hard" },
			{ name = "base16-gruvbox-dark-medium", display = "Base16 Gruvbox Dark Medium" },
			{ name = "base16-gruvbox-dark-pale", display = "Base16 Gruvbox Dark Pale" },
			{ name = "base16-gruvbox-dark-soft", display = "Base16 Gruvbox Dark Soft" },
			{ name = "base16-gruvbox-dark", display = "Base16 Gruvbox Dark" },
			{ name = "base16-gruvbox-light-hard", display = "Base16 Gruvbox Light Hard" },
			{ name = "base16-gruvbox-light-medium", display = "Base16 Gruvbox Light Medium" },
			{ name = "base16-gruvbox-light-soft", display = "Base16 Gruvbox Light Soft" },
			{ name = "base16-gruvbox-light", display = "Base16 Gruvbox Light" },
			{ name = "base16-gruvbox-material-dark-hard", display = "Base16 Gruvbox Material Dark Hard" },
			{ name = "base16-gruvbox-material-dark-medium", display = "Base16 Gruvbox Material Dark Medium" },
			{ name = "base16-gruvbox-material-dark-soft", display = "Base16 Gruvbox Material Dark Soft" },
			{ name = "base16-gruvbox-material-light-hard", display = "Base16 Gruvbox Material Light Hard" },
			{ name = "base16-gruvbox-material-light-medium", display = "Base16 Gruvbox Material Light Medium" },
			{ name = "base16-gruvbox-material-light-soft", display = "Base16 Gruvbox Material Light Soft" },
			{ name = "base16-hardcore", display = "Base16 Hardcore" },
			{ name = "base16-harmonic-dark", display = "Base16 Harmonic Dark" },
			{ name = "base16-harmonic-light", display = "Base16 Harmonic Light" },
			{ name = "base16-harmonic16-dark", display = "Base16 Harmonic16 Dark" },
			{ name = "base16-harmonic16-light", display = "Base16 Harmonic16 Light" },
			{ name = "base16-heetch-light", display = "Base16 Heetch Light" },
			{ name = "base16-heetch", display = "Base16 Heetch" },
			{ name = "base16-helios", display = "Base16 Helios" },
			{ name = "base16-hopscotch", display = "Base16 Hopscotch" },
			{ name = "base16-horizon-dark", display = "Base16 Horizon Dark" },
			{ name = "base16-horizon-light", display = "Base16 Horizon Light" },
			{ name = "base16-horizon-terminal-dark", display = "Base16 Horizon Terminal Dark" },
			{ name = "base16-horizon-terminal-light", display = "Base16 Horizon Terminal Light" },
			{ name = "base16-humanoid-dark", display = "Base16 Humanoid Dark" },
			{ name = "base16-humanoid-light", display = "Base16 Humanoid Light" },
			{ name = "base16-ia-dark", display = "Base16 Ia Dark" },
			{ name = "base16-ia-light", display = "Base16 Ia Light" },
			{ name = "base16-icy", display = "Base16 Icy" },
			{ name = "base16-irblack", display = "Base16 Irblack" },
			{ name = "base16-isotope", display = "Base16 Isotope" },
			{ name = "base16-jabuti", display = "Base16 Jabuti" },
			{ name = "base16-kanagawa-dragon", display = "Base16 Kanagawa Dragon" },
			{ name = "base16-kanagawa", display = "Base16 Kanagawa" },
			{ name = "base16-katy", display = "Base16 Katy" },
			{ name = "base16-kimber", display = "Base16 Kimber" },
			{ name = "base16-lime", display = "Base16 Lime" },
			{ name = "base16-linux-vt", display = "Base16 Linux Vt" },
			{ name = "base16-macintosh", display = "Base16 Macintosh" },
			{ name = "base16-marrakesh", display = "Base16 Marrakesh" },
			{ name = "base16-materia", display = "Base16 Materia" },
			{ name = "base16-material-darker", display = "Base16 Material Darker" },
			{ name = "base16-material-lighter", display = "Base16 Material Lighter" },
			{ name = "base16-material-palenight", display = "Base16 Material Palenight" },
			{ name = "base16-material-vivid", display = "Base16 Material Vivid" },
			{ name = "base16-material", display = "Base16 Material" },
			{ name = "base16-measured-dark", display = "Base16 Measured Dark" },
			{ name = "base16-measured-light", display = "Base16 Measured Light" },
			{ name = "base16-mellow-purple", display = "Base16 Mellow Purple" },
			{ name = "base16-mexico-light", display = "Base16 Mexico Light" },
			{ name = "base16-mocha", display = "Base16 Mocha" },
			{ name = "base16-monokai", display = "Base16 Monokai" },
			{ name = "base16-moonlight", display = "Base16 Moonlight" },
			{ name = "base16-mountain", display = "Base16 Mountain" },
			{ name = "base16-nebula", display = "Base16 Nebula" },
			{ name = "base16-nord-light", display = "Base16 Nord Light" },
			{ name = "base16-nord", display = "Base16 Nord" },
			{ name = "base16-nova", display = "Base16 Nova" },
			{ name = "base16-ocean", display = "Base16 Ocean" },
			{ name = "base16-oceanicnext", display = "Base16 Oceanicnext" },
			{ name = "base16-one-light", display = "Base16 One Light" },
			{ name = "base16-onedark-dark", display = "Base16 Onedark Dark" },
			{ name = "base16-onedark", display = "Base16 Onedark" },
			{ name = "base16-outrun-dark", display = "Base16 Outrun Dark" },
			{ name = "base16-oxocarbon-dark", display = "Base16 Oxocarbon Dark" },
			{ name = "base16-oxocarbon-light", display = "Base16 Oxocarbon Light" },
			{ name = "base16-pandora", display = "Base16 Pandora" },
			{ name = "base16-papercolor-dark", display = "Base16 Papercolor Dark" },
			{ name = "base16-papercolor-light", display = "Base16 Papercolor Light" },
			{ name = "base16-paraiso", display = "Base16 Paraiso" },
			{ name = "base16-pasque", display = "Base16 Pasque" },
			{ name = "base16-penumbra-dark-contrast-plus-plus", display = "Base16 Penumbra Dark Contrast Plus Plus" },
			{ name = "base16-penumbra-dark-contrast-plus", display = "Base16 Penumbra Dark Contrast Plus" },
			{ name = "base16-penumbra-dark", display = "Base16 Penumbra Dark" },
			{ name = "base16-penumbra-light-contrast-plus-plus", display = "Base16 Penumbra Light Contrast Plus Plus" },
			{ name = "base16-penumbra-light-contrast-plus", display = "Base16 Penumbra Light Contrast Plus" },
			{ name = "base16-penumbra-light", display = "Base16 Penumbra Light" },
			{ name = "base16-phd", display = "Base16 Phd" },
			{ name = "base16-pico", display = "Base16 Pico" },
			{ name = "base16-pinky", display = "Base16 Pinky" },
			{ name = "base16-pop", display = "Base16 Pop" },
			{ name = "base16-porple", display = "Base16 Porple" },
			{ name = "base16-precious-dark-eleven", display = "Base16 Precious Dark Eleven" },
			{ name = "base16-precious-dark-fifteen", display = "Base16 Precious Dark Fifteen" },
			{ name = "base16-precious-light-warm", display = "Base16 Precious Light Warm" },
			{ name = "base16-precious-light-white", display = "Base16 Precious Light White" },
			{ name = "base16-primer-dark-dimmed", display = "Base16 Primer Dark Dimmed" },
			{ name = "base16-primer-dark", display = "Base16 Primer Dark" },
			{ name = "base16-primer-light", display = "Base16 Primer Light" },
			{ name = "base16-purpledream", display = "Base16 Purpledream" },
			{ name = "base16-qualia", display = "Base16 Qualia" },
			{ name = "base16-railscasts", display = "Base16 Railscasts" },
			{ name = "base16-rebecca", display = "Base16 Rebecca" },
			{ name = "base16-rose-pine-dawn", display = "Base16 Rose Pine Dawn" },
			{ name = "base16-rose-pine-moon", display = "Base16 Rose Pine Moon" },
			{ name = "base16-rose-pine", display = "Base16 Rose Pine" },
			{ name = "base16-saga", display = "Base16 Saga" },
			{ name = "base16-sagelight", display = "Base16 Sagelight" },
			{ name = "base16-sakura", display = "Base16 Sakura" },
			{ name = "base16-sandcastle", display = "Base16 Sandcastle" },
			{ name = "base16-schemer-dark", display = "Base16 Schemer Dark" },
			{ name = "base16-schemer-medium", display = "Base16 Schemer Medium" },
			{ name = "base16-selenized-black", display = "Base16 Selenized Black" },
			{ name = "base16-selenized-dark", display = "Base16 Selenized Dark" },
			{ name = "base16-selenized-light", display = "Base16 Selenized Light" },
			{ name = "base16-selenized-white", display = "Base16 Selenized White" },
			{ name = "base16-seti", display = "Base16 Seti" },
			{ name = "base16-shades-of-purple", display = "Base16 Shades Of Purple" },
			{ name = "base16-shadesmear-dark", display = "Base16 Shadesmear Dark" },
			{ name = "base16-shadesmear-light", display = "Base16 Shadesmear Light" },
			{ name = "base16-shapeshifter", display = "Base16 Shapeshifter" },
			{ name = "base16-silk-dark", display = "Base16 Silk Dark" },
			{ name = "base16-silk-light", display = "Base16 Silk Light" },
			{ name = "base16-snazzy", display = "Base16 Snazzy" },
			{ name = "base16-solarflare-light", display = "Base16 Solarflare Light" },
			{ name = "base16-solarflare", display = "Base16 Solarflare" },
			{ name = "base16-solarized-dark", display = "Base16 Solarized Dark" },
			{ name = "base16-solarized-light", display = "Base16 Solarized Light" },
			{ name = "base16-spaceduck", display = "Base16 Spaceduck" },
			{ name = "base16-spacemacs", display = "Base16 Spacemacs" },
			{ name = "base16-sparky", display = "Base16 Sparky" },
			{ name = "base16-standardized-dark", display = "Base16 Standardized Dark" },
			{ name = "base16-standardized-light", display = "Base16 Standardized Light" },
			{ name = "base16-stella", display = "Base16 Stella" },
			{ name = "base16-still-alive", display = "Base16 Still Alive" },
			{ name = "base16-summercamp", display = "Base16 Summercamp" },
			{ name = "base16-summerfruit-dark", display = "Base16 Summerfruit Dark" },
			{ name = "base16-summerfruit-light", display = "Base16 Summerfruit Light" },
			{ name = "base16-synth-midnight-dark", display = "Base16 Synth Midnight Dark" },
			{ name = "base16-synth-midnight-light", display = "Base16 Synth Midnight Light" },
			{ name = "base16-tango", display = "Base16 Tango" },
			{ name = "base16-tarot", display = "Base16 Tarot" },
			{ name = "base16-tender", display = "Base16 Tender" },
			{ name = "base16-terracotta-dark", display = "Base16 Terracotta Dark" },
			{ name = "base16-terracotta", display = "Base16 Terracotta" },
			{ name = "base16-tokyo-city-dark", display = "Base16 Tokyo City Dark" },
			{ name = "base16-tokyo-city-light", display = "Base16 Tokyo City Light" },
			{ name = "base16-tokyo-city-terminal-dark", display = "Base16 Tokyo City Terminal Dark" },
			{ name = "base16-tokyo-city-terminal-light", display = "Base16 Tokyo City Terminal Light" },
			{ name = "base16-tokyo-night-dark", display = "Base16 Tokyo Night Dark" },
			{ name = "base16-tokyo-night-light", display = "Base16 Tokyo Night Light" },
			{ name = "base16-tokyo-night-moon", display = "Base16 Tokyo Night Moon" },
			{ name = "base16-tokyo-night-storm", display = "Base16 Tokyo Night Storm" },
			{ name = "base16-tokyo-night-terminal-dark", display = "Base16 Tokyo Night Terminal Dark" },
			{ name = "base16-tokyo-night-terminal-light", display = "Base16 Tokyo Night Terminal Light" },
			{ name = "base16-tokyo-night-terminal-storm", display = "Base16 Tokyo Night Terminal Storm" },
			{ name = "base16-tokyodark-terminal", display = "Base16 Tokyodark Terminal" },
			{ name = "base16-tokyodark", display = "Base16 Tokyodark" },
			{ name = "base16-tomorrow-night-eighties", display = "Base16 Tomorrow Night Eighties" },
			{ name = "base16-tomorrow-night", display = "Base16 Tomorrow Night" },
			{ name = "base16-tomorrow", display = "Base16 Tomorrow" },
			{ name = "base16-tube", display = "Base16 Tube" },
			{ name = "base16-twilight", display = "Base16 Twilight" },
			{ name = "base16-unikitty-dark", display = "Base16 Unikitty Dark" },
			{ name = "base16-unikitty-light", display = "Base16 Unikitty Light" },
			{ name = "base16-unikitty-reversible", display = "Base16 Unikitty Reversible" },
			{ name = "base16-uwunicorn", display = "Base16 Uwunicorn" },
			{ name = "base16-valua", display = "Base16 Valua" },
			{ name = "base16-vesper", display = "Base16 Vesper" },
			{ name = "base16-vice", display = "Base16 Vice" },
			{ name = "base16-vulcan", display = "Base16 Vulcan" },
			{ name = "base16-windows-10-light", display = "Base16 Windows 10 Light" },
			{ name = "base16-windows-10", display = "Base16 Windows 10" },
			{ name = "base16-windows-95-light", display = "Base16 Windows 95 Light" },
			{ name = "base16-windows-95", display = "Base16 Windows 95" },
			{ name = "base16-windows-highcontrast-light", display = "Base16 Windows Highcontrast Light" },
			{ name = "base16-windows-highcontrast", display = "Base16 Windows Highcontrast" },
			{ name = "base16-windows-nt-light", display = "Base16 Windows Nt Light" },
			{ name = "base16-windows-nt", display = "Base16 Windows Nt" },
			{ name = "base16-woodland", display = "Base16 Woodland" },
			{ name = "base16-xcode-dusk", display = "Base16 Xcode Dusk" },
			{ name = "base16-zenbones", display = "Base16 Zenbones" },
			{ name = "base16-zenburn", display = "Base16 Zenburn" },
		},
	},
	{
		name = "falcon",
		repo = "fenetikm/falcon",
		description = "A colour scheme for terminals, Vim and friends.",
		tags = { "dark", "colorful" },
		install_path = "falcon",
	},
	{
		name = "neosolarized",
		repo = "Tsuzat/NeoSolarized.nvim",
		description = "NeoSolarized colorscheme with full transparency.",
		tags = { "dark", "transparent" },
		install_path = "NeoSolarized.nvim",
	},
	{
		name = "nvim-solarized-lua",
		repo = "ishan9299/nvim-solarized-lua",
		description = "Solarized colorscheme in Lua (Neovim >= 0.5).",
		tags = { "dark", "light" },
		install_path = "nvim-solarized-lua",
		custom_name = "solarized",
		variants = {
			{ name = "solarized-flat", display = "Solarized Flat" },
			{ name = "solarized-high", display = "Solarized High" },
			{ name = "solarized-low", display = "Solarized Low" },
			{ name = "solarized", display = "Solarized" },
		},
	},
	{
		name = "dracula",
		repo = "dracula/vim",
		description = "Famous beautiful dark powered theme.",
		tags = { "dark", "vibrant" },
		install_path = "dracula",
	},
	{
		name = "dracula-nvim",
		repo = "Mofiqul/dracula.nvim",
		description = "Dracula colorscheme for Neovim written in Lua.",
		tags = { "dark", "vibrant" },
		install_path = "dracula.nvim",
		custom_name = "dracula",
		variants = {
			{ name = "dracula-soft", display = "Dracula Soft" },
			{ name = "dracula", display = "Dracula" },
		},
	},
	{
		name = "github-nvim-theme",
		repo = "projekt0n/github-nvim-theme",
		description = "A GitHub theme, kitty, alacritty written in Lua. Support built-in LSP and Tree-sitter.",
		tags = { "dark", "light", "treesitter" },
		install_path = "github-nvim-theme",
		custom_name = "github_dark",
		variants = {
			{ name = "github_dark", display = "Github Dark" },
			{ name = "github_dark_colorblind", display = "Github Dark Colorblind" },
			{ name = "github_dark_default", display = "Github Dark Default" },
			{ name = "github_dark_dimmed", display = "Github Dark Dimmed" },
			{ name = "github_dark_high_contrast", display = "Github Dark High Contrast" },
			{ name = "github_dark_tritanopia", display = "Github Dark Tritanopia" },
			{ name = "github_light", display = "Github Light" },
			{ name = "github_light_colorblind", display = "Github Light Colorblind" },
			{ name = "github_light_default", display = "Github Light Default" },
			{ name = "github_light_high_contrast", display = "Github Light High Contrast" },
			{ name = "github_light_tritanopia", display = "Github Light Tritanopia" },
		},
	},
	{
		name = "monochrome",
		repo = "kdheepak/monochrome.nvim",
		description = "A 16 bit monochrome colorscheme that uses hsluv for perceptually distinct gray colors, with support for Tree-sitter and other commonly used plugins.",
		tags = { "monochrome", "dark", "treesitter" },
		install_path = "monochrome.nvim",
	},
	{
		name = "kanagawa-paper",
		repo = "thesimonho/kanagawa-paper.nvim",
		description = "Remixed light and dark Kanagawa colourschemes with muted colors.",
		tags = { "dark", "light", "muted" },
		install_path = "kanagawa-paper.nvim",
		variants = {
			{ name = "kanagawa-paper-canvas", display = "Kanagawa Paper Canvas" },
			{ name = "kanagawa-paper-ink", display = "Kanagawa Paper Ink" },
			{ name = "kanagawa-paper", display = "Kanagawa Paper" },
		},
	},
	{
		name = "tokyodark",
		repo = "tiagovla/tokyodark.nvim",
		description = "A clean dark theme written in Lua (Neovim >= 0.5) and above.",
		tags = { "dark", "clean" },
		install_path = "tokyodark.nvim",
	},
	{
		name = "one_monokai",
		repo = "cpea2506/one_monokai.nvim",
		description = "One Monokai theme written in Lua.",
		tags = { "dark", "vibrant" },
		install_path = "one_monokai.nvim",
	},
	{
		name = "zenburn",
		repo = "phha/zenburn.nvim",
		description = "A low-contrast dark colorscheme with support for various plugins.",
		tags = { "dark", "low-contrast" },
		install_path = "zenburn.nvim",
	},
	{
		name = "rasmus",
		repo = "kvrohit/rasmus.nvim",
		description = "A dark color scheme written in Lua ported from rsms/sublime-theme theme.",
		tags = { "dark" },
		install_path = "rasmus.nvim",
	},
	{
		name = "arctic",
		repo = "rockyzhang24/arctic.nvim",
		description = "A Neovim colorscheme ported from VSCode Dark+ theme with the strict and precise color picking for both the editor and UI.",
		tags = { "dark", "vibrant" },
		requires_lush = true,
		install_path = "arctic.nvim",
	},
	{
		name = "mellifluous",
		repo = "ramojus/mellifluous.nvim",
		description = "Pleasant and productive colorscheme.",
		tags = { "dark", "calm" },
		install_path = "mellifluous.nvim",
	},
	{
		name = "minimal",
		repo = "Yazeed1s/minimal.nvim",
		description = "Two Tree-sitter supported colorschemes that are inspired by base16-tomorrow-night and monokai-pro.",
		tags = { "dark", "treesitter" },
		install_path = "minimal.nvim",
		variants = {
			{ name = "minimal-base16", display = "Minimal Base16" },
			{ name = "minimal", display = "Minimal" },
		},
	},
	{
		name = "adwaita",
		repo = "Mofiqul/adwaita.nvim",
		description = "Colorscheme based on GNOME Adwaita syntax with support for popular plugins.",
		tags = { "dark", "light" },
		install_path = "adwaita.nvim",
	},
	{
		name = "poimandres",
		repo = "olivercederborg/poimandres.nvim",
		description = "Neovim port of poimandres VSCode theme with Tree-sitter support, written in Lua.",
		tags = { "dark", "treesitter" },
		install_path = "poimandres.nvim",
	},
	{
		name = "mellow",
		repo = "mellow-theme/mellow.nvim",
		description = "A soothing dark color scheme with Tree-sitter support.",
		tags = { "dark", "calm", "treesitter" },
		install_path = "mellow.nvim",
	},
	{
		name = "oh-lucy",
		repo = "Yazeed1s/oh-lucy.nvim",
		description = "Two Tree-sitter supported colorschemes, inspired by oh-lucy in vscode.",
		tags = { "dark", "light", "treesitter" },
		install_path = "oh-lucy.nvim",
		variants = {
			{ name = "oh-lucy-evening", display = "Oh Lucy Evening" },
			{ name = "oh-lucy", display = "Oh Lucy" },
		},
	},
	{
		name = "embark",
		repo = "embark-theme/vim",
		description = "A deep inky purple theme leveraging bright colors.",
		tags = { "dark", "purple", "vibrant" },
		install_path = "vim",
	},
	{
		name = "nvimgelion",
		repo = "nyngwang/nvimgelion",
		description = "Neon Genesis Evangelion but for Vimmers.",
		tags = { "dark", "vibrant" },
		install_path = "nvimgelion",
	},
	{
		name = "fluoromachine",
		repo = "maxmx03/fluoromachine.nvim",
		description = "Synthwave x Fluoromachine port.",
		tags = { "dark", "vibrant", "synthwave" },
		install_path = "fluoromachine.nvim",
	},
	{
		name = "midnight",
		repo = "dasupradyumna/midnight.nvim",
		description = "A modern black Neovim theme with comfortable color contrast for a pleasant visual experience, with LSP and Tree-sitter support.",
		tags = { "dark", "modern", "treesitter" },
		install_path = "midnight.nvim",
	},
	{
		name = "citruszest",
		repo = "zootedb0t/citruszest.nvim",
		description = "A colorscheme that features a combination of bright and juicy colors reminiscent of various citrus fruits, with LSP and Tree-sitter support.",
		tags = { "dark", "vibrant", "treesitter" },
		install_path = "citruszest.nvim",
	},
	{
		name = "deepwhite",
		repo = "Verf/deepwhite.nvim",
		description = "A light colorscheme inspired by flatwhite-syntax and elegant-emacs.",
		tags = { "light", "clean" },
		install_path = "deepwhite.nvim",
	},
	{
		name = "monokai-nightasty",
		repo = "polirritmico/monokai-nightasty.nvim",
		description = "A dark/light theme based on the Monokai color palette written in Lua, support for LSP, Tree-sitter and lots of plugins.",
		tags = { "dark", "light", "vibrant" },
		install_path = "monokai-nightasty.nvim",
	},
	{
		name = "modus-themes",
		repo = "miikanissi/modus-themes.nvim",
		description = "Accessible theme, conforming with the highest standard for color contrast (WCAG AAA).",
		tags = { "dark", "light", "high-contrast" },
		install_path = "modus-themes.nvim",
		custom_name = "modus",
		variants = {
			{ name = "modus", display = "Modus" },
			{ name = "modus_operandi", display = "Modus Operandi" },
			{ name = "modus_vivendi", display = "Modus Vivendi" },
		},
	},
	{
		name = "hybrid",
		repo = "HoNamDuong/hybrid.nvim",
		description = "A dark theme written in Lua.",
		tags = { "dark" },
		install_path = "hybrid.nvim",
	},
	{
		name = "lackluster",
		repo = "slugbyte/lackluster.nvim",
		description = "A delightful mostly grayscale colorscheme that is soft on the eyes, and supports heaps of plugins.",
		tags = { "monochrome", "dark", "minimal" },
		install_path = "lackluster.nvim",
		variants = {
			{ name = "lackluster-dark", display = "Lackluster Dark" },
			{ name = "lackluster-hack", display = "Lackluster Hack" },
			{ name = "lackluster-mint", display = "Lackluster Mint" },
			{ name = "lackluster-night", display = "Lackluster Night" },
			{ name = "lackluster", display = "Lackluster" },
		},
	},
	{
		name = "neofusion",
		repo = "diegoulloao/neofusion.nvim",
		description = "A theme compatible with Tree-sitter inspired by gruvbox.nvim.",
		tags = { "dark", "warm", "treesitter" },
		install_path = "neofusion.nvim",
	},
	{
		name = "kanso",
		repo = "webhooked/kanso.nvim",
		description = "Kansō is an elegant evolution of the original Kanagawa theme. A dark theme that invites focus, not attention.",
		tags = { "dark", "minimal" },
		install_path = "kanso.nvim",
		variants = {
			{ name = "kanso-ink", display = "Kanso Ink" },
			{ name = "kanso-mist", display = "Kanso Mist" },
			{ name = "kanso-pearl", display = "Kanso Pearl" },
			{ name = "kanso-zen", display = "Kanso Zen" },
			{ name = "kanso", display = "Kanso" },
		},
	},
	{
		name = "no-clown-fiesta",
		repo = "aktersnurra/no-clown-fiesta.nvim",
		description = "A dark gray colorscheme",
		tags = { "dark", "minimal" },
		install_path = "no-clown-fiesta.nvim",
	},
	{
		name = "solarized-osaka",
		repo = "craftzdog/solarized-osaka.nvim",
		description = "🏯 A clean, dark Neovim theme written in Lua, with support for lsp, treesitter and lots of plugins. ",
		tags = { "dark" },
		install_path = "solarized-osaka.nvim",
		variants = {
			{ name = "solarized-osaka", display = "solarized osaka" },
			{ name = "solarized-osaka-day", display = "solarized osaka day" },
		},
	},
}
