name: docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: theme-hub
          version: "Neovim >= 0.7.0"
          demojify: true
          treesitter: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore(docs): auto-generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_options: "--no-verify"
